with open("test2.txt","w") as f:
    f.write("helllooooooo\n")
    f.write("everyone\n")
    f.write("-N\n")
    print("is the file closed :",f.closed)
print("is the file closed:",f.close())
name=input("enter your name:")
age=input("eneter your age:")
f=open("test2.txt","a")
f.write("this is me trying to append stuff\n")
f.write("this was successful\n")
print("more data appended to rhe file")
f.write(name)
f.write(age)
f.close()